
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qgzx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rikka233
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 30MB
#      max-request-size: 30MB
#
#file.upload.dir =
Logging:
  level:
    com.zjj: debug